version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  mongodb_be:
    build:
      context: ./mongodb_be
      dockerfile: Dockerfile
    container_name: mongodb_be
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/uditdb
      - JWT_SECRET=your_jwt_secret_key
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=yashs3324@gmail.com
      - EMAIL_PASS=avhszmzkkkfqjtwa
      - EMAIL_FROM=yashs3324@gmail.com
      - CLIENT_URL=http://localhost:3000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
